-- Execute este script no SQL Editor do Supabase

create table if not exists public.motores (
  id bigint generated by default as identity primary key,
  numero_motor varchar(100) not null,
  modelo varchar(120) not null,
  potencia varchar(50) not null,
  tensao varchar(50) not null,
  corrente varchar(50) not null,
  data_registro timestamptz not null default now(),
  responsavel varchar(120) not null,
  observacoes text
);

create index if not exists idx_motores_data_registro on public.motores (data_registro desc);

-- Se voce for usar CRUD direto do frontend com chave anon, habilite RLS e politicas.
-- Em producao, restrinja as politicas conforme suas regras de seguranca.

alter table public.motores enable row level security;

create policy if not exists "Allow select motores" on public.motores
for select
to anon, authenticated
using (true);

create policy if not exists "Allow insert motores" on public.motores
for insert
to anon, authenticated
with check (true);

create policy if not exists "Allow update motores" on public.motores
for update
to anon, authenticated
using (true)
with check (true);

create policy if not exists "Allow delete motores" on public.motores
for delete
to anon, authenticated
using (true);
